### ISSUE TITLE
Relationship between Treatment and treatment types

### ISSUE THREAD

**Issue by kcranston** [CanDIG/MOHCCN_clinical_data_model#2]
Based on some conversations with Hardeep, we have been using these relationships between Treatments and the treatment types:

* one Treatment can be linked to multiple Chemotherapies (for example, if the treatment included multiple drugs). Or, stated another way, multiple Chemotherapy entries can have the same `submitter_treatment_id`
* one Treatment can be linked to multiple Immunotherapies
* one Treatment can only be linked to a single Surgery entry
* one Treatment can only be linked to a single Radiation entry

We are seeing some data that have multiple Radiation entries linked to a single Treatment id. Is that valid or not?

**Comment by Emjvdl** [comment]
I think possible for Radiation to have more than one entry only if there was a "Radiation Boost"

**Comment by kcranston** [comment]
Closing this issue, because I think the changes in v3.0 with the new System Therapy table address this question.
